[package]
name = 'spinup'
version = '0.1.0'
authors = ['Steve Pentland <stevepentland@gmail.com>']
edition = '2018'
license = 'MIT'

[dependencies]
clap = '2.33'
log = '0.4'

[dependencies.libspinup]
path = '../libspinup'

[dependencies.tokio]
version = '0.2'
features = ['macros']
