name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Clippy
        uses: icepuma/rust-action@1.39.0
        with:
          args: cargo clippy --verbose
      - name: Build
        uses: icepuma/rust-action@1.39.0
        with:
          args: cargo build --verbose
      - name: Run tests
        uses: icepuma/rust-action@1.39.0
        with:
          args: cargo test --verbose
